Restaurant/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('', views.home, name = 'home'),
    path('rest/', views.restdata_show, name = 'rest'),
    path('login_page/', views.login_page, name = 'login_page'),
    path('logoutpage/', views.logoutpage, name='logoutpage'),
    path("register/", views.register_request, name="register"),
    path("menu/", views.search, name="menu"),
    path('detail/<int:pk>/',views.detail, name = 'details'),

    

    
    
]

home/models.py
from statistics import mode
from django.contrib.auth.models import User
from email.mime import image
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils.translation import gettext as _
from django.shortcuts import get_object_or_404
# Create your models here.
    
class Restaurant(models.Model):
    name = models.CharField(_("name") ,max_length = 255)
    area = models.CharField(_("area"), max_length = 255)
    cuisines = models.CharField(_("cuisines"), max_length = 255)
    cost_for_Two = models.BigIntegerField(_("costForTwo"))
    address = models.CharField(_("address"), max_length = 255)
    locality = models.CharField(_("locality"), max_length = 25)
    avgRating = models.FloatField(_("avgRating"), max_length = 25)
    picture = models.ImageField(upload_to = "static/images/" , default = "/static/images/dess1.png")
    desciption = models.CharField(blank=True, null =True, max_length = 500)
    
    
    def __str__(self):
        return self.name   
    
    class Meta:
        db_table = "rest_data"
        
class Review(models.Model):
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    name = models.ForeignKey(Restaurant, related_name='reviews', on_delete=models.CASCADE)
    content = models.TextField(max_length = 250, blank = True, null=True)
    stars = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content


    
    

home/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User




# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user



class CuisineChoiceField(forms.Form):

    cuisines = forms.ModelChoiceField(
        queryset=Restaurant.objects.values_list("cuisines", flat=True).distinct(),
        #empty_label=None
    )
    

class LocationChoiceField(forms.Form):

    area = forms.ModelChoiceField(
        queryset=Restaurant.objects.values_list("area", flat=True).distinct(),
        #empty_label=None
    )
    
    
    

home/views.py
from multiprocessing import context
from unicodedata import name
from urllib import request
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from .forms import LocationChoiceField, NewUserForm , CuisineChoiceField
from .models import  Restaurant,Review
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request):
    # data = Restaurant.objects.all()
    # context = {''}
    return render(request, 'index.html')

def login_page(request):
    if request.method == 'POST':
        name = request.POST['name']
        password = request.POST['password']
        
        user = authenticate(request, username=name, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            print("error 404: credentials not found")
            return redirect('login_page')
    return render(request, 'log1.html')  # made chnages here for login temp


def logoutpage(request):
    logout(request)
    return redirect('home')

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect("home")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})

def restdata_show(request):
    data = Restaurant.objects.all()
    # print(data[1])
    context = {"restd": data}
    return render(request, 'restdata.html', context)

@login_required(login_url="login_page")
def search(request):

    cuisine_list = CuisineChoiceField()
    area_list = LocationChoiceField()
    if request.GET.get('cuisines') and request.GET.get('area'):
        selected_cuisine = request.GET.get('cuisines')
        selected_area = request.GET.get('area')
        query_results = Restaurant.objects.filter(cuisines = selected_cuisine,
                                                  area = selected_area)
    else:
        query_results = Restaurant.objects.all()
    context = {
        'query_results': query_results,
        'cuisine_list': cuisine_list,
        'area_list' : area_list,
    }
    return render(request,'menu.html', context)


@login_required(login_url="login_page")
def detail(request,pk):
    fetchData = Restaurant.objects.get(id=pk)   
    all_reviews = Review.objects.all()
    # print(review)
    
    name = get_object_or_404(Restaurant, id=pk)
    
    if request.method == "POST":
        stars = request.POST.get('stars',3)
        content = request.POST.get('content', '')
        review = Review.objects.create( user=request.user,name = name, content=content,stars=stars)
        review.save()
    context = {"fetchData":fetchData,"all_reviews":all_reviews}
                
        
    return render(request, 'rest_detail.html', context)

templates/log1.html
{% load static %}

<!Doctype html>
<html lang="en">
  <head>
  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{% static 'csss/style.css' %}">

	</head>
	<body class="img js-fullheight" style="background-image: url(/static/images/brooke-lark-wMzx2nBdeng-unsplash.jpg);">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<h3 class="mb-4 text-center">Have an account?</h3>
		      	<form action="#" class="signin-form" method="post">
					{% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" class="form-control" placeholder="Username" required name= "name">
		      		</div>
	            <div class="form-group">
	              <input id="password-field" type="password" class="form-control" name = "password" placeholder="Password" required>
	              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
		            	<label class="checkbox-wrap checkbox-primary">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="#" style="color: #fff">Forgot Password</a>
								</div>
	            </div>
	          </form>
	          <p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
	          <div class="social d-flex text-center">
	          	<a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
	          	<a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
	          </div>
		      </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js1/jquery.min.js' %}"></script>
  <script src="{% static 'js1/popper.js' %}"></script>
  <script src="{% static 'js1/bootstrap.min.js' %}"></script>
  <script src="{% static 'js1/main.js' %}"></script>

	</body>
</html>

templates/menu.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Food </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'bootstrap/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'bootstrap/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'bootstrap/responsive.css' %}" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
  <link href="{% static 'css/main.css' %}" rel="stylesheet" />

</head>
<body class="sub_page">
<!-- 

<div class="container" style="width: 100% ; ">    
  <div style ="height: 100%; width:100% ; color:rgb(245, 246, 236); background-color: rgb(15, 11, 1)"  class="container">
  <div>Choose the cuisine</div>
  <form method="get" action="{% url 'menu' %}" style="width: 100%">
      {{ cuisine_list }}
      <button class="btn btn-white shadow-warning text-warning" type="submit" style="color: rgb(244, 244, 244)">Submit</button>
  </form>
  </div>
</div> -->

<div class="s130">
  <form method="get" action="{% url 'menu' %}">
    <!-- {{ cuisine_list }} -->
    <div class="inner-form">
      <div class="input-field first-wrap">
        <div class="svg-wrapper">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
          </svg>
        </div>
        <!-- <input id="search" type="text" placeholder="What are you looking for?" /> -->
        <select name="cuisines" required="" id="id_cuisines" style="width : 100% ; height:70% ; background-color:#d9f1e3">
          <option value="" selected="" >---------</option>   
          {% for i in cuisine_list %}  
          <option value={{i}}></option>   
          {% endfor %}
        </select>
        <select name="area" required="" id="id_area" style="width : 100% ; height:70% ; background-color:#d9f1e3">
          <option value="" selected="" >---------</option>   
          {% for i in area_list %}  
          <option value={{i}}></option>   
          {% endfor %}
        </select>
      </div>
      <div class="input-field second-wrap">
        <button class="btn-search" type="submit">SEARCH</button>
      </div>
    </div>
    <!-- <span class="info">ex. Game, Music, Video, Photography</span> -->
  </form>
</div>

  <section class="food_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Restaurants
        </h2>
      </div>

      <div class="filters-content">
        <div class="row grid">
          {% for item in query_results %}
          <div class="col-sm-6 col-lg-4 all pizza" >
            <div class="box">
              <div  style="background-color: #dfa904">
                <div class="img-box">
                  <a href="{% url 'details' item.id %}"><img src="{{item.picture.url}}" alt="" ></a>
                </div>
                <div class="detail-box">
                  <h5>
                    {{item.name}}
                  </h5>
                  <p>
                    Ratings : {{item.avgRating}}  
                  </p>
                  <div class="options">
                    <h6>
                      Price for two : Rs {{item.cost_for_Two}}<br/>
                      Locality : {{item.locality}}<br/>
                      Area : {{item.area}}
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <!-- <div class="btn-box">
        <a href="">
          View More
        </a>
      </div>
    </div> -->
  </section>

  

  <!-- end food section -->


  <!-- jQery -->
  <script src="{% static 'js1/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js1/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js1/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>

</html>

templates/register.html
<!-- {% extends './common/base.html' %} -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
<!-- {% block content %}  -->
{% load crispy_forms_tags %}         
<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'login_page' %}">login</a> instead.</p>
</div>

<!-- {% endblock %} -->

</body>
</html>

templates/rest_detail.html
{% extends './common/base.html' %}


{% load static %}


{% block content %}

    <section class="py-5 overflow-hidden bg-primary" id="home" style="height: 500px; background: url(/static/images/banner1.jpg); background-size:100%; background-repeat:no-repeat; background-position:center; margin-top: 50px;">
      </section>
      <div class="col-lg-7 mx-auto text-center mb-6" style="background-color:white; width:100%">
        <h5 class="fw-bold fs-3 fs-lg-5 lh-sm mb-3" style="margin-top: 50px; ">Restaurant Detail</h5>
      </div>
    <section id = 'restdetails' class="section-p1" style="background-color:white">
        <div class="single-rest-image" style="background-color:white;">
            <img src="{{fetchData.picture.url}}" width="100%" id="MainImg" alt="">
        </div>
        <div class = "single-rest-details">
            <h4> {{fetchData.name}}</h4><br>
            <h2> Cost For Two: {{fetchData.cost_for_Two}} </h2><br>
            <h2>Description</h2>
            <span>
                {{fetchData.desciption}}
            </span>
        </div>
    </section>

    <div class="rev-section" style="margin: auto;padding: 0 1rem;max-width: 1100px;text-align: center;">
        <h2 class="title" style=" font-size: 2.5rem;text-transform: uppercase;color: rgb(50, 50, 50);margin-bottom: .5rem;">REVIEWS</h2>
    </div>


    <div class="reviews-box" style="display:flex;justify-content:center;align-items:center;flex-wrap:wrap;width:100%;float:left">
        <div class="review box" style="width:500px;box-shadow:2px 2px 30px rgba(0,0,0,0.1); background-color:#ffffff;padding:20px;margin:15px;cursor:pointer">
            
            {% for i in all_reviews %}        
            {% if fetchData.name == i.name.name %}      
            <div class="box-top" style="display: flex; justify-content:space-between; align-items:center; margin-bottom:20px">
                <div class="profile" style="display: flex; align-items:center">
                    <div class="name-user" style="display: flex; flex-direction:column">
                        <strong style="color:#3d3d3d; font-size:1.1rem; letter-spacing:0.5px">{{ i.user }}</strong>
                    </div>
                </div>
                <div class="reviews" style="color: #f9d71c;">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                </div>
            </div>

            <div class="comment">
                <p style="font-size:0.9rem;color:#4b4b4b">{{ i.content }}
                </p>
            </div>
            {% endif %}
         {% endfor%}


        </div>
    </div><br>

    
        <div class="container-fluid py-4">
            <div class="container pt-5 pb-3"><br>
                <h2 class="display-4 text-uppercase text-center mb-5">Write your review</h2>
                <div class="row" style=" display:flex;justify-content:center">
                    <div class="col-lg-7 mb-2 align-items-center justify-content-center;display:flex">
                        <div  style="padding: 30px; background-color: beige; display:flex;justify-content:center">
                            <form action = "" method="post">
                                {% csrf_token %}

                                <div class="row">
                                    <!-- <div class="col-6 form-group">
                                        <input type="text" class="form-control p-4" placeholder="Your Name" required="required">
                                    </div> -->
                                    <div class="col-6 form-group">
                                        <input type="number" class="form-control p-4" placeholder="Rate this website" required="required">
                                    </div>
                                    <div class="form-group">
                                        <textarea class="form-control py-3 px-4" rows="5" placeholder="Review" name="content" required="required"></textarea>
                                    </div>
                                    <div>
                                        <button class="btn btn-primary py-3 px-5" type="submit">Submit Review</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

templates/restaurant.html
{% load static %}
<form class="row gx-2 gy-2 align-items-center" method="get" action="{% url 'wo' %}">
    <div class="col">
      <div class="input-group-icon"><i class="fas fa-map-marker-alt text-danger input-box-icon"></i>
        <label class="visually-hidden" for="inputDelivery">Address</label>
        <!-- <input class="form-control input-box form-foodwagon-control" id="inputDelivery" type="text" placeholder="Enter Your Location" name="area"/> -->
        <select name="area" required="" id="id_area" style=" background-color:#d9f1e3">
          <option value="" selected="" >---------</option>   
          {% for i in area_list %}  
          <option  value= {{i}} ></option>   
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="d-grid gap-3 col-sm-auto">
      <button class="btn btn-danger" type="submit">Find Restaurant</button>
    </div>
  </form>





<div class="container" style="width: 100% ; ">    
    <!-- <div style ="height: 100%; width:100% ; color:rgb(3, 3, 2) " class="container">
    <div>Choose the Area</div>
    <form method="get" action= "{% url 'wo' %}" style="width: 100%">
        {{ area_list }}
        <button class="btn btn-white shadow-warning text-warning" type="submit" style="color: rgb(169, 121, 206)">Submit</button>
    </form>
    </div>
  </div> -->

<div class = 'container'>
    <table>
        {% for i in results %}
        <tr>
            <td>{{i.name}}</td>
            <td>{{i.avgRating}}</td>
            <td>{{i.area}}</td>
        </tr>
        {% endfor %}
    </table>
</div>

templates/restdata.html
{% extends './common/base.html' %}

{% load static %} 

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicons/favicon.ico' %}">
    <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" />

</head> -->
<!-- <body> -->
    {% block content %}
    
    <section class="food_section layout_padding">
      <div class="container">
        <div class="heading_container heading_center">
          <h2>
            Restaurants
          </h2>
        </div>
  
        <div class="filters-content">
          <div class="row grid">
            {% for item in restd %}
            <div class="col-sm-6 col-lg-4 all pizza" >
              <div class="box">
                <div  style="background-color: #dfa904">
                  <div class="img-box">
                    <a href="{% url 'details' item.id %}"><img src="{{item.picture.url}}" alt="" ></a> 
                  </div>
                  <div class="detail-box" >
                    <h5 style="color:white; font-size: 1.55rem">
                      {{item.name}}
                    </h5>
                    <p style="color:white;font-size: 15px">
                      Ratings : {{item.avgRating}}  
                    </p>
                    <div class="options">
                      <h6 style="color:white; font-size:17px; width:fit-content">
                        Price for two : Rs {{item.cost_for_Two}}<br/>
                        Locality : {{item.locality}}<br/>
                        Area : {{item.area}}
                      </h6>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <!-- <div class="btn-box">
          <a href="">
            View More
          </a>
        </div>
      </div> -->
    </section>


  
    

    {% endblock%}
<!-- 
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/is.min.js' %}"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script> -->

<!-- </body> -->
<!-- </html> -->